DISCOUNT_FACTOR = 0.99
HIDDEN_DIMENSIONS = 128  # TODO vedere se altre dimensioni funzionano meglio
DROPOUT = 0.2
NUM_TEST = 5
MODE='rgb_array'
BATCH_SIZE = 256
INPUT_FEATURES = 84 * 84
ACTOR_OUTPUT_FEATURES = 5
CRITIC_OUTPUT_FEATURES = 1

# PARAMETRI PER I TEST
MAX_EPISODES = 200
PRINT_INTERVAL = 5
TEST_INTERVAL = 15
N_TRIALS = 3
REWARD_THRESHOLD = 50

# PARAMETRI DA MODIFICARE PER ESPLORAZIONE
ENTROPY_COEFFICIENT = 0.3    # Aumentato da 0.2
LEARNING_RATE = 0.0003       # Aumentato da 0.0001
EPSILON = 0.25               # Leggermente aumentato da 0.2
PPO_STEPS = 8